# Example config file for synthesize.py
# Edit parameters as needed


preset: ultra_fast # Options: ultra_fast, fast, standard, high_quality
randomness: 0.5 # Lower values will produce more consistent results, higher values will produce more varied results
sample_cache: "basic.pt"
reference_folder: "voices/Default"

