# Example config file for synthesize.py
# Edit parameters as needed


preset: standard # Options: ultra_fast, fast, standard, high_quality
randomness: 0.1 # Lower values will produce more consistent results, higher values will produce more varied results
sample_cache: "New_Voice.pt"
reference_folder: "Training"
